name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AlexxNB/caprover-action@v1
        with:
          server: 'https://captain.majapi.com'
          password: '${{ secrets.CAPROVER_PASSWORD }}'
          appname: 'italodeandra'
          branch: 'main'
